const cancionesRespaldo = Array.isArray(canciones) ? canciones.slice() : [];
let catalogoCanciones = cancionesRespaldo.slice();
const ordenLiturgico=["Entrada","Perdon","Gloria","Antifona","Colecta","Ofertorio","Santo","Padre","Cordero","Comunion","ComunionII","Salida","Himno"];
let listaActual=[],seleccion={},ordenCelebracion=[],indiceCelebracion=0,categoriaAbierta=null;
let modoSeleccion="personal"; // personal | compartida
let perfilSesion=null;

function catalogo(){return catalogoCanciones}
function claveLocal(){return modoSeleccion==="personal"?"miCelebracion":"celebracionCompartidaCache"}
function puedeEditarCompartida(){return !!perfilSesion&&perfilSesion.activo===true&&["ADMINISTRADOR","COLABORADOR"].includes(perfilSesion.rol)}
function cargar(categoria){if(categoriaAbierta===categoria){categoriaAbierta=null;listaActual=[];document.getElementById("listaCanciones").innerHTML="";document.getElementById("buscador").value="";return}categoriaAbierta=categoria;listaActual=catalogo().filter(c=>c.categoria===categoria);document.getElementById("buscador").value="";mostrarCanciones(listaActual)}
function mostrarCanciones(datos){const bloqueado=modoSeleccion==="compartida"&&!puedeEditarCompartida();document.getElementById("listaCanciones").innerHTML=datos.map(c=>`<div class="cancion" ${bloqueado?'style="opacity:.75" title="Celebración compartida: solo lectura"':`onclick="seleccionar(${c.id},'${String(c.categoria).replace(/'/g,"\\'")}')"`}>${seleccion[c.categoria]?.id===c.id?"✅ ":""}${c.titulo}</div>`).join("")}
function seleccionar(id,cat){if(modoSeleccion==="compartida"&&!puedeEditarCompartida()){alert("La celebración compartida es de solo lectura. Inicia sesión como colaborador o administrador para modificarla.");return}const c=catalogo().find(x=>x.id===id&&(!cat||x.categoria===cat));if(!c)return;seleccion[c.categoria]=c;guardarSeleccion();actualizarSeleccion();mostrarCanciones(listaActual)}
function quitarCancion(cat){if(modoSeleccion==="compartida"&&!puedeEditarCompartida())return;delete seleccion[cat];guardarSeleccion();actualizarSeleccion();mostrarCanciones(listaActual)}
function actualizarSeleccion(){const bloqueado=modoSeleccion==="compartida"&&!puedeEditarCompartida();document.getElementById("listaSeleccion").innerHTML=ordenLiturgico.map(cat=>seleccion[cat]?`<div class="itemSeleccion completo"><b>✅ ${cat}</b><br>${seleccion[cat].titulo}${bloqueado?'':`<br><br><button onclick="quitarCancion('${cat}')">❌ Quitar</button>`}</div>`:`<div class="itemSeleccion incompleto"><b>⬜ ${cat}</b><br>Sin seleccionar</div>`).join("");actualizarPanelModo()}
function guardarSeleccion(){localStorage.setItem(claveLocal(),JSON.stringify(seleccion));if(modoSeleccion==="compartida"&&puedeEditarCompartida())window.dispatchEvent(new CustomEvent("celebracion-compartida-cambiada",{detail:Object.fromEntries(Object.entries(seleccion).map(([cat,c])=>[cat,c.id]))}))}
function aplicarIds(ids,guardar=true){seleccion={};for(const[cat,id]of Object.entries(ids||{})){const c=catalogo().find(x=>x.id===Number(id)&&x.categoria===cat);if(c)seleccion[cat]=c}if(guardar)localStorage.setItem(claveLocal(),JSON.stringify(seleccion));actualizarSeleccion();if(categoriaAbierta){listaActual=catalogo().filter(c=>c.categoria===categoriaAbierta);mostrarCanciones(listaActual)}}
window.aplicarCelebracionCompartida=(ids)=>{localStorage.setItem("celebracionCompartidaIds",JSON.stringify(ids||{}));if(modoSeleccion==="compartida")aplicarIds(ids)};
function cargarSeleccionLocal(){seleccion={};try{const d=JSON.parse(localStorage.getItem(claveLocal())||"{}");for(const[cat,v]of Object.entries(d)){const id=typeof v==="object"?v.id:v;const c=catalogo().find(x=>x.id===Number(id)&&x.categoria===cat);if(c)seleccion[cat]=c}}catch(e){}actualizarSeleccion()}
function cambiarModo(nuevo){modoSeleccion=nuevo;if(nuevo==="personal")cargarSeleccionLocal();else{let ids={};try{ids=JSON.parse(localStorage.getItem("celebracionCompartidaIds")||"{}")}catch(e){}aplicarIds(ids,false)}actualizarSeleccion();mostrarCanciones(listaActual)}
window.cambiarModoCelebracion=cambiarModo;
window.actualizarPerfilSesion=(p)=>{perfilSesion=p||null;actualizarPanelModo();actualizarSeleccion();mostrarCanciones(listaActual)};
function nuevaCelebracion(){if(modoSeleccion==="compartida"&&!puedeEditarCompartida()){alert("Solo colaboradores y administradores pueden cambiar la celebración compartida.");return}if(confirm(modoSeleccion==="personal"?"¿Borrar Mi celebración?":"¿Borrar la celebración compartida?")){seleccion={};ordenCelebracion=[];indiceCelebracion=0;guardarSeleccion();actualizarSeleccion();mostrarCanciones(listaActual)}}
function buscar(){const t=document.getElementById("buscador").value.trim().toLowerCase();listaActual=catalogo().filter(c=>[c.titulo,c.autor,c.categoria].some(v=>(v||"").toLowerCase().includes(t)));mostrarCanciones(listaActual)}
function iniciarCelebracion(){ordenCelebracion=ordenLiturgico.filter(cat=>seleccion[cat]).map(cat=>seleccion[cat]);if(!ordenCelebracion.length){alert("Seleccione canciones");return}indiceCelebracion=0;mostrarCelebracion();document.getElementById("modoCelebracion").classList.remove("oculto");pantallaCompleta()}
function mostrarCelebracion(){const c=ordenCelebracion[indiceCelebracion];if(!c){cerrarCelebracion();return}document.getElementById("tituloCelebracion").innerHTML=`${c.categoria} · ${c.titulo}<small>&nbsp; (${indiceCelebracion+1} de ${ordenCelebracion.length})</small>`;const el=document.getElementById("letraCelebracion");el.innerText=c.letra;el.scrollTo({top:0,behavior:"smooth"})}
function siguiente(){if(indiceCelebracion<ordenCelebracion.length-1){indiceCelebracion++;mostrarCelebracion()}}
function anterior(){if(indiceCelebracion>0){indiceCelebracion--;mostrarCelebracion()}}
function cerrarCelebracion(){document.getElementById("modoCelebracion").classList.add("oculto");if(document.fullscreenElement)document.exitFullscreen()}
function pantallaCompleta(){if(!document.fullscreenElement)document.documentElement.requestFullscreen().catch(console.log);else document.exitFullscreen()}

function crearPanelModo(){if(document.getElementById("panelModoCancionero"))return;const host=document.querySelector("header")||document.body;const p=document.createElement("div");p.id="panelModoCancionero";p.style.cssText="display:flex;gap:6px;align-items:center;flex-wrap:wrap;padding:6px 10px;background:#fff;color:#222;border-radius:8px;margin:4px;box-shadow:0 1px 5px #0002;font-size:13px";host.appendChild(p);actualizarPanelModo()}
function actualizarPanelModo(){const p=document.getElementById("panelModoCancionero");if(!p)return;const usuario=perfilSesion?`${perfilSesion.nombre||perfilSesion.email} · ${perfilSesion.rol}`:"Visitante";p.innerHTML=`<button onclick="cambiarModoCelebracion('personal')" ${modoSeleccion==='personal'?'disabled':''}>👤 Mi celebración</button><button onclick="cambiarModoCelebracion('compartida')" ${modoSeleccion==='compartida'?'disabled':''}>👥 Compartida</button><span>${usuario}</span><button id="btnSesionCancionero">${perfilSesion?'Cerrar sesión':'Iniciar sesión'}</button>`;document.getElementById("btnSesionCancionero").onclick=()=>window.dispatchEvent(new CustomEvent(perfilSesion?"solicitar-logout":"solicitar-login"))}

window.addEventListener("catalogo-cargado",e=>{const nuevo=e.detail?.canciones;catalogoCanciones=Array.isArray(nuevo)&&nuevo.length?nuevo:cancionesRespaldo.slice();if(modoSeleccion==="personal")cargarSeleccionLocal();else{let ids={};try{ids=JSON.parse(localStorage.getItem("celebracionCompartidaIds")||"{}")}catch(e){}aplicarIds(ids,false)}console.log(`Catálogo cargado desde ${e.detail?.origen}: ${catalogoCanciones.length} entradas`)});
document.addEventListener("DOMContentLoaded",()=>{crearPanelModo();cargarSeleccionLocal();actualizarSeleccion()});
if(document.readyState!=="loading"){crearPanelModo();cargarSeleccionLocal();actualizarSeleccion()}
